### PR TITLE
:construction: Add the number of person with the same note as you

### PR DESCRIPTION
**Pull request by fantomitechno**
Motivation: knowing your rank can help but sometimes you don't know if a lot of persons have the same notes as you

- [x] Need a better visual\
for now it's only : `$rank/$total [$nbWithSameGrade]

### CODE REVIEW

**Review by GabrielPlayeur — CHANGES_REQUESTED** [review]
After the tests, it's best to calculate numberOfSameNotes as follows :
`function getPersonnalRank(grades, studentGrade) {
    grades.sort(function(a,b) { return b - a;});
    firstIndex = grades.indexOf(studentGrade)+1;
    lastIndex = grades.lastIndexOf(studentGrade)+1;
    return [firstIndex, lastIndex-firstIndex+1];
}`

**Comment by fantomitechno** [comment]
> After the tests, it's best to calculate numberOfSameNotes as follows :
> `function getPersonnalRank(grades, studentGrade) {
>     grades.sort(function(a,b) { return b - a;});
>     firstIndex = grades.indexOf(studentGrade)+1;
>     lastIndex = grades.lastIndexOf(studentGrade)+1;
>     return [firstIndex, lastIndex-firstIndex+1];
> }`

Updated to comply with these + changed to use less "+1" because subtracting n+1 to m+1 felt unnecessary to me

**Comment by fantomitechno** [comment]
Wait after rethinking about it, I realised wouldn't it be clearer for the user to remove every duplicated grades from the list for example:
```js
let grades = [10, 12, 13, 10, 12];
let userGrade = 10;
```
now it will render: `4/5 [2]`

but it could go with: `3/3 [2]`
🤔

**Comment by GabrielPlayeur** [comment]
I don't think so, there are 140 students. I think it's less clear if there are only 100 grades appear. Maybe we just need to find a clearer way of saying that there are several people with the same grade?

**Comment by fantomitechno** [comment]
probably... but the place is very limited 😓... maybe like a hover thingy? but css is hard

**Pull request merged**
